const orderData = [
  {
    customerId: 701,
    customerName: 'John',
    customerMobileNumber: '8171845998',
    storeKeeperId: 801,
    deliveryAddressId: 21,
    address: 'newDelhi,110001',
    landmark: 'Near XYZ School',
    orderId: 1,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Fresh Bananas',
        unit: 'PKT',
        quantity: 2,
        price: 0.0,
      },
      {
        itemId: 2,
        itemName: 'Organic Tomatoes',
        unit: 'ML',
        quantity: 1,
        price: 0.0,
      },
      {
        itemId: 3,
        itemName: 'Whole Milk',
        unit: 'ML',
        quantity: 1,
        price: 0.0,
      },
      {
        itemId: 4,
        itemName: 'Fresh Bananas',
        unit: 'PKT',
        quantity: 8,
        price: 0.0,
      },
      {
        itemId: 5,
        itemName: 'Brown Bread',
        unit: 'ML',
        quantity: 10,
        price: 0.0,
      },
      {
        itemId: 6,
        itemName: 'Organic Tomatoes',
        unit: 'ML',
        quantity: 2,
        price: 0.0,
      },
      {
        itemId: 7,
        itemName: 'Brown Bread',
        unit: 'ML',
        quantity: 2,
        price: 0.0,
      },
      {
        itemId: 8,
        itemName: 'Whole Milk',
        unit: 'ML',
        quantity: 3,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
  {
    customerId: 702,
    customerName: 'Marco',
    customerMobileNumber: '9985771849',
    storeKeeperId: 802,
    deliveryAddressId: 22,
    address: 'newDelhi,110001',
    landmark: 'Near XYZ Park',
    orderId: 2,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Whole Milk',
        unit: 'ML',
        quantity: 10,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
  {
    customerId: 703,
    customerName: 'Rishab',
    customerMobileNumber: '8195775849',
    storeKeeperId: 803,
    deliveryAddressId: 23,
    address: 'newDelhi,110001',
    landmark: 'Near XYZ Hospital',
    orderId: 3,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Brown Bread',
        unit: 'ML',
        quantity: 2,
        price: 0.0,
      },
      {
        itemId: 2,
        itemName: 'Whole Milk',
        unit: 'ML',
        quantity: 10,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
  {
    customerId: 704,
    customerName: 'Jacob',
    customerMobileNumber: '8176872709',
    storeKeeperId: 804,
    deliveryAddressId: 24,
    address: 'newDelhi,110001',
    landmark: 'Near XYZ Police',
    orderId: 4,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Organic Tomatoes',
        unit: 'ML',
        quantity: 9,
        price: 0.0,
      },
      {
        itemId: 2,
        itemName: 'Whole Milk',
        unit: 'ML',
        quantity: 8,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
  {
    customerId: 705,
    customerName: 'Rohan',
    customerMobileNumber: '7069548249',
    storeKeeperId: 805,
    deliveryAddressId: 25,
    address: 'newDelhi,110001',
    landmark: 'Near Metro',
    orderId: 5,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Brown Bread',
        unit: 'ML',
        quantity: 9,
        price: 0.0,
      },
      {
        itemId: 2,
        itemName: 'Organic Tomatoes',
        unit: 'ML',
        quantity: 7,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
  {
    customerId: 706,
    customerName: 'Sonia',
    customerMobileNumber: '8059357496',
    storeKeeperId: 806,
    deliveryAddressId: 26,
    address: 'newDelhi,110001',
    landmark: 'Near Bus Station',
    orderId: 6,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Brown Bread',
        unit: 'ML',
        quantity: 6,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
  {
    customerId: 707,
    customerName: 'Danny',
    customerMobileNumber: '9581839548',
    storeKeeperId: 807,
    deliveryAddressId: 27,
    address: 'newDelhi,110001',
    landmark: 'Near XYZ School',
    orderId: 7,
    orderDate: '2025-07-15T05:46:25',
    items: [
      {
        itemId: 1,
        itemName: 'Fresh Bananas',
        unit: 'PKT',
        quantity: 1,
        price: 0.0,
      },
      {
        itemId: 2,
        itemName: 'Organic Tomatoes',
        unit: 'ML',
        quantity: 5,
        price: 0.0,
      },
      {
        itemId: 3,
        itemName: 'Whole Milk',
        unit: 'ML',
        quantity: 4,
        price: 0.0,
      },
      {
        itemId: 4,
        itemName: 'Fresh Bananas',
        unit: 'PKT',
        quantity: 1,
        price: 0.0,
      },
      {
        itemId: 5,
        itemName: 'Brown Bread',
        unit: 'ML',
        quantity: 1,
        price: 0.0,
      },
    ],
    status: 'PENDING',
    storeKeeperNote: null,
  },
];


export default orderData;
