// src/constants/strings.js

import { set } from 'zod';
import { store } from '../store/store';

const strings = {
  selectUserType: 'Select User Type',

  otpTitle: 'Enter OTP',
  sendOtp: 'Send OTP',
  resendOtp: 'Resend OTP',
  resendOtpAvailable: seconds => `Resend available in ${seconds}s`,
  havnotReceivedOtp: "Haven't received OTP?",
  login: ' Login',
  enterOtp: 'Enter 4 Digit Code Here',
  otpFailed: 'OTP Verification Failed',
  agreeTo: ' I agreed to ',
  termsAndConditions: `Terms and conditions & ${'\n'}Privacy Policy`,

  myProfile: 'My Profile',
  name: 'Name',
  mobile: 'Contact Number',
  addressLine1: 'Address Line 1',
  addressLine2: 'Address Line 2',
  landmark: 'Landmark',
  city: 'City',
  state: 'State',
  pincode: 'Pincode',
  continue: 'Continue',
  email: 'Email',
  dob: 'Date of Birth',
  firstName: 'First Name',
  lastName: 'Last Name',
  storekeeperName: 'Storekeeper Name',
  storeName: 'Store Name',
  gst: 'GST IN',
  uploadStoreImage: 'Upload Store Image',
  storeImage: 'Store Image',
  saveChanges: 'Save Changes',

  myOrders: 'My Orders',

  addStore: 'Add Store',
  tryAgain: 'Please try again',
  verifiedOtp: 'OTP Verified',
  addStoreViaQR: 'Scan QR to Add Store',
  addStoreViaNumber: 'Add Store By Id',
  changeStore: 'Change Store',
  skip: 'Skip',
  noStoresFound: 'No stores found',
  myStores: 'My Stores',

  productCount: totalItems =>
    `${totalItems} item${totalItems > 1 ? 's' : ''} in cart`,
  goToCart: 'Go to Cart',
  checkout: 'Checkout',
  orderPlaced: 'Order Placed',
  noItemsFound: 'No items found.',
  profileSetting: 'Profile Settings',
  cancel: 'Cancel',

  rateStore: 'Rate Store',
  characters: 'characters ',
  submitReview: 'Submit Review',
  thankyou: 'Thank You !',
  appriciateFeedback:
    'We appreciate your feedback. It helps us improve your experience.',
  done: 'Done',
  feedbackPlaceholder: 'Write your feedback here...',

  searchPlaceholder: 'Search here for anything you want...',

  shoppingCart: 'Shopping Cart',
  emptyCart: 'Your cart is empty 🛒',
  browseGrocery: 'Browse Grocery',
  cartTitle: totalCount =>
    `Shopping Cart (${totalCount} ${totalCount > 1 ? 'items' : 'item'})`,
  deliveryAddress: 'Delivery Address',
  addAddress: 'Add Address',
  selectedItems: 'Selected Items',
  proceed: 'Proceed ',
  addMoreItems: 'Add more Items',

  thankyouForPurchase: `Thank you for your purchase. ${'\n'} You can view your order in ‘My Orders’ ${'\n'}section`,
  continueShopping: 'Continue Shopping',

  whatsAppMessage: "Hello, I'm contacting you regarding your order.",

  help: "We're Here to Help You",
  feelFree: 'Feel free to reach out through any of the methods below:',
  callUs: 'Call Us',
  emailUs: 'Email Us',
  chatUs: 'Chat with Us on WhatsApp',
  call: 'Call',
  whatsapp: 'WhatsApp',

  filterOrders: 'Filter Orders',
  clear: 'Clear ',
  priceRange: 'Price Range',
  apply: 'Apply',
  noOrderFound: 'No orders found.',

  orderId: 'Order ID',
  orderStatus: 'Order Status',
  orderDate: 'Order Date',
  totalPrice: ' Total Price :',
  totalItems: 'Total Items :',
  orderItems: 'Order Items',
  orderDetails: 'Order Details',
  orderHistory: 'Order History',
  store: 'Store :',
  customer: 'Customer :',
  repeatOrder: 'Repeat Order',

  paymentOptions: 'Payment Options',
  qrCode: 'QR Code',
  changeQr: 'Change QR Code',
  uploadQr: 'Upload QR Code',
  noQrUploaded: 'No QR Uploaded',
  default: 'Default',
  setDefault: 'Set as Default',
  delete: 'Delete',
  confirm: 'Confirm',
  confirmDeleteQrTitle: 'Delete QR Code',
  confirmDeleteQrMessage: 'Are you sure you want to delete this QR code?',

  noAddressFound: 'No address added',
  markAsDefault: 'Mark as Default',
  changeAddress: 'Change Address',

  noCategoriesFound: 'No categories found',

  //Toast messages
  addedTocart: 'Added to cart',
  failedToAddItem: 'Failed to add item',
  otpResent: 'OTP Resent',
  otpSent: 'OTP Sent',
  invalidOtp: 'Invalid OTP',
  invalidMobile: 'Please enter your mobile number',
  validMobileNumber: 'Mobile number must be exactly 10 digits Mobile number must be exactly 10 digits',
  invalidQr: 'Invalid QR Code',
  invalidQr2: 'Please scan a valid QR code',
  failedToAddStore: 'Failed to add store',
  otpVerified: 'OTP Verified',
  addedStoreSuccessfully: 'Store added successfully',
  registeredSuccessfully: 'Registered Successfully',
  profileCreationFailed: 'Profile creation failed',
  failedToLoadProfile: 'Failed to load profile',
  failedToCreateProfile: 'Failed to create profile',
  provideRatingAndFeedback: 'Please provide both rating and feedback.',
  noStoresFound: 'No stores found. ',
  noStoresFound2: 'Please add or select a store first.',
  failedToSubmitRating: 'Failed to submit rating.',
  failedToLoadItems: 'Failed to load cart items',
  missingAddress1: 'Address Missing',
  missingAddress2: 'Add address before checkout',
  missingStore1: 'Store Missing',
  missingStore2: 'Add or Select Store before checkout',
  missingItems1: 'Items Missing',
  missingItems2: 'Add items before checkout',
  failedToPlaceOrder: 'Failed to place order',
  invalidQty: 'Invalid Quantity',
  uploadFailed: 'Upload Failed',
  couldnotUploadQR: 'Could not upload QR code. Try again.',
  failedToDeleteQR: 'Failed to delete QR code',
  failedTosetDefaultQR: 'Failed to set QR as default',
  profileUpdatedSuccessfully: 'Profile updated successfully',
  failedToUpdateProfile: 'Failed to update profile',
};

export default strings;
