
export const apiEndpoints = {
  ADMIN_LOGIN: `/auth/api/v1/login`,
  GET_ALL_CATEGORIES_WITH_PAGINATION: `/nukkad/api/category/v1/get/all`,
  GET_ALL_CATEGORIES: `/nukkad/api/category/v1/get`,
  CREATE_CATEGORIES: `/nukkad/api/category/v1/create`,
  DELETE_CATEGORY_BY_ID:`/nukkad/api/category/v1/deleteBy/id`,
  GET_PRODUCTS: `/nukkad/api/item/v1/get`,
  CREATE_PRODUCTS:`/nukkad/api/item/v1/create`,
  DELETE_PRODUCT_BY_ID:`/nukkad/api/item/v1/deleteBy/id`,
  IMPORT_EXCEL_PRODUCT_FILE:`/nukkad/api/admin/v1/upload/file`,
  GET_ALL_CUSTOMERS:`/nukkad/api/customer/v1/get/all`,
  GET_CUSTOMER_BY_ID:`/nukkad/api/customer/v1/get/byId`,
  GET_ALL_STOREKEEPERS:`/nukkad/api/storekeeper/v1/get/all`,
  GET_STOREKEEPER_BY_ID:`/nukkad/api/storekeeper/v1/getBy/id`,
  IMPORT_JSON_PRODUCT_FILE:`/nukkad/api/admin/v1/upload/json`,
  DELETE_CUSTOMER_BY_ID:`/nukkad/api/admin/v1/delete/customer`,
  DELETE_STOREKEEPER_BY_ID:`/nukkad/api/admin/v1/delete/storekeeper`,
  GET_PRODUCTS_BY_CATEGORY:`/nukkad/api/item/v1/get_by_category`,
  UPDATE_PRODUCT:`/nukkad/api/item/v1/update`,
  SEARCH:`/nukkad/api/search/v1/get`,
  SEARCH_CATEGORIES:`/nukkad/api/search/v1/get`,
  GET_CATEGORY_BY_ID:`/nukkad/api/category/v1/get`,
};